// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcdiCijkoVCd4J7dU-98ZEe0Sd8qUwGdU',
    appId: '1:954984000000:web:68e70187506cac68cd86e5',
    messagingSenderId: '954984000000',
    projectId: 'login-90694',
    authDomain: 'login-90694.firebaseapp.com',
    storageBucket: 'login-90694.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYd8wkUjDuqux3T8e0sQkE4gpdk26e42Q',
    appId: '1:954984000000:android:72b7302561e71655cd86e5',
    messagingSenderId: '954984000000',
    projectId: 'login-90694',
    storageBucket: 'login-90694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-EMpoLvFDgF975vmCeDfo31T11lkAQ5M',
    appId: '1:954984000000:ios:db3fa8b9cd55f5d1cd86e5',
    messagingSenderId: '954984000000',
    projectId: 'login-90694',
    storageBucket: 'login-90694.appspot.com',
    iosClientId: '954984000000-a3f1ihos9o5mb449rdi9964mt1kmcv4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-EMpoLvFDgF975vmCeDfo31T11lkAQ5M',
    appId: '1:954984000000:ios:438d1af6635867c7cd86e5',
    messagingSenderId: '954984000000',
    projectId: 'login-90694',
    storageBucket: 'login-90694.appspot.com',
    iosClientId: '954984000000-kjgulth57ck2l2hbgi7vsrhd0d7gh9dj.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginfirebase.RunnerTests',
  );
}
